"""Promotion discovery, parsing, validation, optimization and ranking."""

from .models import (
    ALL_STATUSES,
    ALL_TYPES,
    CRITICAL_FIELDS,
    EligibilityStatus,
    Promotion,
    PromotionSource,
    PromotionStatus,
    PromotionTerms,
    PromotionType,
    RewardType,
    Valuation,
)
from .auto_lifecycle import (
    PromotionFacts,
    determine_status,
    gather_facts,
    path_to,
    resolve,
    sync_promotion_lifecycle,
    terms_complete,
)
from .from_row import promotion_from_row
from .lifecycle import (
    ALLOWED_TRANSITIONS,
    CHAIN,
    EXCEPTION_STATES,
    TERMINAL_STATES,
    advance_lifecycle,
    can_transition,
    is_actionable,
    is_terminal,
    is_terms_verified,
)
from .reward_tokens import (
    ALL_TOKEN_STATUSES,
    RewardToken,
    RewardTokenStatus,
    effective_status,
    is_expired,
    is_settled,
    outstanding_face_value,
    pending_conversion_value,
    projected_value,
    realized_value,
)
from .verification import (
    CRITICAL_TERMS,
    VerificationCheck,
    VerificationReport,
    review_issues,
    terms_hash,
    validate_ontario,
)
from .pipeline import (
    CandidateStatus,
    PromotionEvaluation,
    build_demo_pool,
    evaluate_promotion,
    filter_for_promotion,
)
from .optimizer import (
    Candidate,
    best_conversion,
    best_qualifying,
    value_promotion,
)
from .parser import american_to_decimal, parse_odds, parse_terms
from .providers.base import PromotionProvider, RawPromotion
from .providers.manual import ManualPromotionProvider
from .providers.web import WebPromotionProvider
from .ranking import SORT_KEYS, rank_promotions, sequence_promotions
from .validator import promotion_from_terms, validate_terms

__all__ = [
    "ALLOWED_TRANSITIONS",
    "ALL_STATUSES",
    "ALL_TOKEN_STATUSES",
    "ALL_TYPES",
    "CHAIN",
    "CRITICAL_FIELDS",
    "CRITICAL_TERMS",
    "EXCEPTION_STATES",
    "TERMINAL_STATES",
    "Candidate",
    "CandidateStatus",
    "EligibilityStatus",
    "PromotionEvaluation",
    "PromotionFacts",
    "ManualPromotionProvider",
    "Promotion",
    "PromotionProvider",
    "PromotionSource",
    "PromotionStatus",
    "PromotionTerms",
    "PromotionType",
    "RawPromotion",
    "RewardToken",
    "RewardTokenStatus",
    "RewardType",
    "SORT_KEYS",
    "VerificationCheck",
    "VerificationReport",
    "advance_lifecycle",
    "can_transition",
    "create_reward_token",
    "effective_status",
    "is_actionable",
    "is_expired",
    "is_settled",
    "is_terminal",
    "is_terms_verified",
    "outstanding_face_value",
    "pending_conversion_value",
    "projected_value",
    "realized_value",
    "review_issues",
    "terms_hash",
    "validate_ontario",
    "Valuation",
    "WebPromotionProvider",
    "american_to_decimal",
    "best_conversion",
    "best_qualifying",
    "build_demo_pool",
    "determine_status",
    "evaluate_promotion",
    "filter_for_promotion",
    "gather_facts",
    "path_to",
    "resolve",
    "sync_promotion_lifecycle",
    "terms_complete",
    "parse_odds",
    "parse_terms",
    "promotion_from_row",
    "promotion_from_terms",
    "rank_promotions",
    "sequence_promotions",
    "validate_terms",
    "value_promotion",
]
