"""Application services (business logic independent of the UI)."""

from .discovery import (
    DiagnosticCode,
    DiscoveryResult,
    OpportunityStatus,
    classify_recommendation,
    discover_conversion,
    discover_qualifying,
)
from .profit import (
    ProfitView,
    locked_in_range,
    profit_view,
    projected_profit,
    realized_profit,
)
from .profitability import (
    BankrollRequirement,
    ProfitabilityStatus,
    PromotionProfitability,
    StageProfitability,
    bankroll_requirement,
    conversion_support,
    discover_profitability,
    evaluate_profitability,
    rank_profitabilities,
    stage_from_recommendation,
)
from .promotion_workflow import (
    MODES,
    LiveDataUnavailable,
    Recommendation,
    calculate_net_profit,
    confirm_qualifying_settlement,
    confirm_reward_received,
    find_conversion_bets,
    find_qualifying_bets,
    parse_promotion,
    rank_conversion_bets,
    rank_qualifying_bets,
    record_conversion_placed,
    record_qualifying_placed,
    save_promotion,
)
from .workflow import WorkflowState, derive_state, progress_index, sync_workflow

__all__ = [
    "MODES",
    "DiagnosticCode",
    "DiscoveryResult",
    "LiveDataUnavailable",
    "OpportunityStatus",
    "Recommendation",
    "WorkflowState",
    "ProfitView",
    "BankrollRequirement",
    "ProfitabilityStatus",
    "PromotionProfitability",
    "StageProfitability",
    "bankroll_requirement",
    "classify_recommendation",
    "conversion_support",
    "discover_profitability",
    "evaluate_profitability",
    "rank_profitabilities",
    "stage_from_recommendation",
    "discover_conversion",
    "discover_qualifying",
    "locked_in_range",
    "profit_view",
    "projected_profit",
    "realized_profit",
    "calculate_net_profit",
    "confirm_qualifying_settlement",
    "confirm_reward_received",
    "derive_state",
    "find_conversion_bets",
    "find_qualifying_bets",
    "parse_promotion",
    "progress_index",
    "rank_conversion_bets",
    "rank_qualifying_bets",
    "record_conversion_placed",
    "record_qualifying_placed",
    "save_promotion",
    "sync_workflow",
]
